# 玩家首次加入服务器时的传送位置
first-join:
  world: world
  x: 2760
  y: 72
  z: 2453
  yaw: 0.0
  pitch: 0.0

# 玩家没有个人存档点时，插件强制使用该位置进行加入或复活传送
default-respawn:
  world: world
  x: 2760
  y: 72
  z: 2453
  yaw: 0.0
  pitch: 0.0

# 玩家通过床或重生锚更新个人存档点时的提示消息
spawn-update-message:
  chat:
    enabled: true
    text: 已设置重生点
  action-bar:
    enabled: true
    text: 已设置重生点
