# 玩家首次加入服务器时使用的专属出生场景
first-join:
  enabled: true
  group: first-join

# 非首次加入且未命中个人存档点时使用的出生场景
join-default:
  enabled: true
  group: join-default

# 玩家因死亡重生且未命中个人存档点时使用的出生场景
death-respawn:
  enabled: true
  group: death-respawn

# 是否接管玩家通过床/重生锚设置的个人存档点
personal-spawn:
  enabled: true

# 玩家在公共坐标组内无权限命中且没有 Default 兜底时的提示
no-permission-message: 你没有权限

# 玩家通过床或重生锚更新个人存档点时的提示消息
spawn-update-message:
  chat:
    enabled: true
    text: 已设置重生点
  action-bar:
    enabled: true
    text: 已设置重生点